// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoginAttempt struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	Success     bool               `json:"success"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TwoFaCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  pgtype.Int4        `json:"attempts"`
	IsUsed    pgtype.Bool        `json:"is_used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Firstname         string             `json:"firstname"`
	Lastname          string             `json:"lastname"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	TwoFaEnabled      pgtype.Bool        `json:"two_fa_enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BlockedUntil      pgtype.Timestamptz `json:"blocked_until"`
	FailedAttempts    pgtype.Int4        `json:"failed_attempts"`
	LastFailedAttempt pgtype.Timestamptz `json:"last_failed_attempt"`
}

type Board struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	OwnerID     int64              `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Column struct {
	ID        int64              `json:"id"`
	BoardID   int64              `json:"board_id"`
	Title     string             `json:"title"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          int64              `json:"id"`
	BoardID     int64              `json:"board_id"`
	ColumnID    int64              `json:"column_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Position    pgtype.Int4        `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CreateBoardParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	OwnerID     int64  `json:"owner_id"`
}

type UpdateBoardParams struct {
	ID          int64   `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

type CreateColumnParams struct {
	BoardID  int64 `json:"board_id"`
	Title    string `json:"title"`
	Position int32  `json:"position"`
}

type UpdateColumnParams struct {
	ID       int64   `json:"id"`
	Title    *string `json:"title"`
	Position *int32  `json:"position"`
}

type CreateTaskParams struct {
	BoardID     int64             `json:"board_id"`
	ColumnID    *int64            `json:"column_id"`
	Title       string            `json:"title"`
	Description string            `json:"description"`
	Position    *int32            `json:"position"`
}

type UpdateTaskParams struct {
	ID          int64             `json:"id"`
	Title       *string           `json:"title"`
	Description *string           `json:"description"`
	ColumnID    *int64            `json:"column_id"`
	Position    *int32            `json:"position"`
}
