// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BlockUser(ctx context.Context, arg BlockUserParams) error
	CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTwoFaCode(ctx context.Context, arg CreateTwoFaCodeParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, token string) error
	GetBlockedStatus(ctx context.Context, email string) (pgtype.Timestamptz, error)
	GetFailedLogAttempts(ctx context.Context, arg GetFailedLogAttemptsParams) (int64, error)
	GetRecentCodeRequests(ctx context.Context, arg GetRecentCodeRequestsParams) (int64, error)
	GetRecentFailedAttempts(ctx context.Context, arg GetRecentFailedAttemptsParams) (int64, error)
	GetRecentVerificationAttempts(ctx context.Context, arg GetRecentVerificationAttemptsParams) (int64, error)
	GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error)
	GetTwoFaCodeByUserID(ctx context.Context, userID int64) (TwoFaCode, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	MarkTwoFaCodeAsUsed(ctx context.Context, id int64) error
	RefreshDeleteByUserI(ctx context.Context, userID int64) error
	RefreshDeleteByUserID(ctx context.Context, userID int64) error
	ResetFailedAttempts(ctx context.Context, email string) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateTwoFAStatus(ctx context.Context, arg UpdateTwoFAStatusParams) error
	UpdateTwoFaCodeAttempts(ctx context.Context, arg UpdateTwoFaCodeAttemptsParams) error
}

var _ Querier = (*Queries)(nil)
