// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_fa.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTwoFaCode = `-- name: CreateTwoFaCode :one
INSERT INTO two_fa_codes (
    user_id,
    code,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id
`

type CreateTwoFaCodeParams struct {
	UserID    int64              `json:"user_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTwoFaCode(ctx context.Context, arg CreateTwoFaCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTwoFaCode, arg.UserID, arg.Code, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRecentCodeRequests = `-- name: GetRecentCodeRequests :one
SELECT COUNT(*) as count
FROM two_fa_codes 
WHERE user_id = $1 
  AND created_at >= $2
`

type GetRecentCodeRequestsParams struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentCodeRequests(ctx context.Context, arg GetRecentCodeRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentCodeRequests, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentVerificationAttempts = `-- name: GetRecentVerificationAttempts :one
SELECT COUNT(*) as count
FROM two_fa_codes 
WHERE user_id = $1 
  AND created_at >= $2 
  AND attempts > 0
`

type GetRecentVerificationAttemptsParams struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentVerificationAttempts(ctx context.Context, arg GetRecentVerificationAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentVerificationAttempts, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTwoFaCodeByUserID = `-- name: GetTwoFaCodeByUserID :one
SELECT 
    id,
    user_id,
    code,
    expires_at,
    attempts,
    is_used,
    created_at
FROM two_fa_codes 
WHERE user_id = $1 
  AND is_used = false 
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC 
LIMIT 1
`

func (q *Queries) GetTwoFaCodeByUserID(ctx context.Context, userID int64) (TwoFaCode, error) {
	row := q.db.QueryRow(ctx, getTwoFaCodeByUserID, userID)
	var i TwoFaCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.Attempts,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const markTwoFaCodeAsUsed = `-- name: MarkTwoFaCodeAsUsed :exec
UPDATE two_fa_codes 
SET is_used = true 
WHERE id = $1
`

func (q *Queries) MarkTwoFaCodeAsUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markTwoFaCodeAsUsed, id)
	return err
}

const updateTwoFaCodeAttempts = `-- name: UpdateTwoFaCodeAttempts :exec
UPDATE two_fa_codes 
SET attempts = $2 
WHERE id = $1
`

type UpdateTwoFaCodeAttemptsParams struct {
	ID       int64       `json:"id"`
	Attempts pgtype.Int4 `json:"attempts"`
}

func (q *Queries) UpdateTwoFaCodeAttempts(ctx context.Context, arg UpdateTwoFaCodeAttemptsParams) error {
	_, err := q.db.Exec(ctx, updateTwoFaCodeAttempts, arg.ID, arg.Attempts)
	return err
}
